---

- name: MY AS3 PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    uri_method: POST
  
  vars_files:
  - ../creds/big_creds.yaml
  tasks:

  - name: ASchmidt_CreateApplication
    uri:
      url: https://3.11.134.160/mgmt/shared/appsvcs/declare
      user: "{{ bigip_user }}"
      password: "{{ bigip_password }}"
      method: "{{ uri_method }}"
      body: "{{ lookup('file','as3-declaration.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: as3_response

  - name: DEBUG AS3 OUTPUT
    debug:
      msg: "{{ as3_response.json.declaration.Andy_Schmidt}}"

...